# <span style="color:red">Wichtiger Hinweis: Dieses Notebook erst später anschauen!</span>

### Dieses Notebook zeigt dir, wie ich die Daten aufbereitet habe. Dabei verwende ich aber Funktionen, die du zum aktuellen Zeitpunkt noch nicht kennst. 

### Dieses Notebook dient primär der Vollständigkeit - und damit du dich (nach Abschluss des Kurses) überzeugen kannst, dass es sich bei den Daten tatsächlich um echte Daten handelt ;) 

### Ich empfehle dir, dieses Notebook dir erst später im Verlauf des Kurses nochmal anzuschauen!

In [2]:
import pandas as pd

df = pd.read_csv("../data/autos.csv", encoding="ISO-8859-1")

df.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

In [4]:
df = df[["price", "yearOfRegistration", "powerPS", "kilometer", "model", "fuelType", "name", "gearbox"]]

# Dann filtern wir unrealistische Daten heraus
df = df[df["price"] < 50000]
df = df[df["price"] > 0]
df = df[df["powerPS"] < 300]
df = df[df["powerPS"] > 30]
df = df[df["yearOfRegistration"] < 2020]
df = df[df["yearOfRegistration"] > 1970]

# Einen Kilometerstand von 150.000km haben erstaunlich viele Autos. Theorie: Autos mit 300.000km werden auch unter 150.000km geführt
df = df[df["kilometer"] <= 140000]

In [5]:
df.to_csv("./autos_cross_val.csv.bz2", compression = "bz2", index = False)